### PR TITLE
Fix #183: Fix inconsistent mouse events on search interface

### LINKED ISSUE #183: the search item click event works inconsistently – either it doesn't work at all or sometimes it selects another item
I had thought this bug was fixed, but it turns out it wasn't.

### PR DESCRIPTION
**Pull request by openjck**

### CODE REVIEW

File: src/app/sections/Search.svelte [hunk 1]
```diff
@@ -16,27 +13,26 @@ let inputElement;
...
-    store.setField('searchIsActive', true);
+  store.setField('searchIsActive', true);
 }
 
-function turnOffSearch() {
-    setTimeout(() => {
-      store.setField('searchIsActive', false);
-    }, 100);
+function turnOffSearch(evt) {
+  console.log(evt);
```
Comment (spasovski) [inline src/app/sections/Search.svelte]: we can remove this

**Review by spasovski — CHANGES_REQUESTED** [review]
I would clean up the console log and any editor-introduced whitespace that you don't want there. Tested just fine locally I think the main idea of removing the input blur event was a good call.

File: src/app/sections/Search.svelte (hunk 1 above)
Comment (openjck) [reply src/app/sections/Search.svelte]: Whoops, thanks!

**Comment by openjck** [comment]
Updated. Anything else before we merge?

File: src/app/sections/Search.svelte [hunk 2]
```diff
@@ -135,12 +141,12 @@ async function onKeypress(event) {
       {/if}
     </div>
     <input 
+      type="search"
       aria-autocomplete="list"
       aria-controls="telemetry-search-results" 
       on:focus={turnOnSearch}
       bind:this={inputElement}
       placeholder="search for a telemetry probe"
-      on:blur={turnOffSearch}
```
Comment (spasovski) [inline src/app/sections/Search.svelte:143]: Seems we'll no longer need the `turnOffSearch()` function above since we set the store directly.

File: src/app/sections/Search.svelte [hunk 3]
```diff
@@ -20,9 +20,7 @@ function turnOnSearch() {
 }
 
 function turnOffSearch() {
```
Comment (spasovski) [inline src/app/sections/Search.svelte]: Likely candidate for removal - or call this in the event handler below.

**Review by spasovski — CHANGES_REQUESTED** [review]
r+wc

File: src/app/sections/Search.svelte (hunk 2 above)
Comment (openjck) [reply src/app/sections/Search.svelte:143]: Yep, good call. Thank you!
