### PR TITLE
Fix violins

### LINKED ISSUE #202: fix violin element implementation
The curve function used to produce the violin plots that doesn't properly extend to the edges of the distribution.

It would be fairly easy to take d3's implementation of the curve and add a few tweaks.

### PR DESCRIPTION
**Pull request by hamilton**
closes #202.

I'm going to do a bit more QA on this to make sure I can cover more of the edge cases. Scalars are still pretty broken overall but this _will_ (1) show bin, and (2) default to a 1 or 2px line when the bin widths are infinitesimal. At that resolution it is better to just show a 1px line than nothing at all.

### CODE REVIEW

File: src/components/explore/AdHocViolin.svelte [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+$: offset = density.map((di, i) => ($yScale.type === 'scalePoint' ? $yScale.step() / 2 : spacing[i] / 2));
+$: pos = direction > 0;
+
+</script>
+
+<g style="transform: translateX({start}px); fill: {color};">
+  {#each density as {bin, value}, i (`${bin}-${value}`)}
+      <rect x={pos ? 0 : width - x(value)} y={$yScale(bin) - offset[i] - 0.1} width={x(value)} height={Math.max(2, spacing[i] + 0.2)} />
+  {/each}
+</g>
```
Comment (openjck) [inline src/components/explore/AdHocViolin.svelte:42]: Just so that I understand it better, can you say more about the filename? What makes it ad-hoc?

File: src/components/explore/ProbeExplorer.svelte [hunk 2]
```diff
@@ -225,10 +227,18 @@ $: if (hoverValue.x) {
...
     <!-- add violin plots on the quantiles -->
 
-    <g slot='body' let:left={lp} let:right={rp}>
+    <g slot='glam-body' let:top let:bottom let:left={lp} let:right={rp} let:yScale>
       {#if showViolins}
+        <line
+          x1={(lp + rp) / 2} x2={(lp + rp) / 2} y1={top} y2={bottom} stroke=var(--digital-blue-150)
+        />
         {#if hovered.datum || insufficientData}
-          <Violin
```
Comment (openjck) [inline src/components/explore/ProbeExplorer.svelte:231]: Now that we're not using `Violin`, we're getting this on line 5:

```
  5:8  error  'Violin' is defined but never used  no-unused-vars
```

File: src/components/explore/ProbeExplorer.svelte [hunk 3]
```diff
@@ -260,7 +278,7 @@ $: if (hoverValue.x) {
               - explorerComparisonSmallMultiple.right) / 2 - 5]}
             areaColor="var(--digital-blue-400)"
             lineColor="var(--digital-blue-500)"
-          />
+          /> -->
```
Comment (openjck) [inline src/components/explore/ProbeExplorer.svelte]: Can we remove lines 264-281 or do we want to keep them for reference?

File: src/components/explore/ProbeExplorer.svelte [hunk 4]
```diff
@@ -241,12 +251,20 @@ $: if (hoverValue.x) {
               (explorerComparisonSmallMultiple.width
               - explorerComparisonSmallMultiple.left
               - explorerComparisonSmallMultiple.right) / 2 - 5]}
-            areaColor="var(--digital-blue-400)"
-            lineColor="var(--digital-blue-500)"
-          />
+            areaColor="var(--pantone-red-400)"
+            lineColor="var(--pantone-red-500)"
+          /> -->
```
Comment (openjck) [inline src/components/explore/ProbeExplorer.svelte]: Can we remove lines 241-256 or do we want to keep them for reference?

**Review by openjck — CHANGES_REQUESTED** [review]

File: src/components/explore/ProbeExplorer.svelte [hunk 5]
```diff
@@ -241,12 +251,20 @@ $: if (hoverValue.x) {
...
         {/if}
-        {#if reference}
-          <Violin
+        {#if reference && reference[densityMetricType]}
+              <AdHocViolin start={(lp + rp) / 2} density={reference[densityMetricType]}
+                width={
+                  (explorerComparisonSmallMultiple.width
+                - explorerComparisonSmallMultiple.left
+                - explorerComparisonSmallMultiple.right) / 2 - 7} />
```
Comment (openjck) [inline src/components/explore/ProbeExplorer.svelte]: I think the magic constant of 7 is throwing me off a bit. What's the significance of that?

File: src/components/explore/ProbeExplorer.svelte [hunk 6]
```diff
@@ -225,10 +227,18 @@ $: if (hoverValue.x) {
...
+        <line
+          x1={(lp + rp) / 2} x2={(lp + rp) / 2} y1={top} y2={bottom} stroke=var(--digital-blue-150)
+        />
         {#if hovered.datum || insufficientData}
-          <Violin
+        <AdHocViolin start={lp + 5} direction={-1} density={insufficientData ? data[0][densityMetricType] : hovered.datum[densityMetricType]}
+          width={
+            (explorerComparisonSmallMultiple.width
+          - explorerComparisonSmallMultiple.left
+          - explorerComparisonSmallMultiple.right) / 2 - 6} />
```
Comment (openjck) [inline src/components/explore/ProbeExplorer.svelte]: Same with 6

File: src/components/explore/ProbeExplorer.svelte (hunk 5 above)
Comment (hamilton) [reply src/components/explore/ProbeExplorer.svelte]: eyeballing mostly

Comment (hamilton) [reply src/components/explore/ProbeExplorer.svelte]: I'll move thse into variable names

File: src/components/explore/AdHocViolin.svelte (hunk 1 above)
Comment (hamilton) [reply src/components/explore/AdHocViolin.svelte:42]: I wanted to make it clear that this implementation is ad hoc right now, and should not be moved elsewhere or re-used right now until we figure out if this is a good approach.
