### PR TITLE
Fix #959: Make extracting bug IDs more robust

### LINKED ISSUE #959: Fenix: Support Github issue links in metric details sidebar
Currently the links for bugs and data reviews assume a bugzilla URL. We should support both bugzilla and github style URLs so we provide an accurate link name for the links.

### PR DESCRIPTION
**Pull request by robhudson**
Before | After
------ | -----
Screenshot_2020-10-16 network_cache_hit_time GLAM(1) | Screenshot_2020-10-16 network_cache_hit_time GLAM
Screenshot_2020-10-16 storage_stats_cache_bytes GLAM(2) | Screenshot_2020-10-16 storage_stats_cache_bytes GLAM(1)

### CODE REVIEW

File: src/utils/urls.js [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+    const match = /id=(\d+)/.exec(url);
+    if (match) {
+      return match[1];
+    }
+    return url;
+  }
+  if (url.includes('github')) {
+    const match = /(issues|pull)\/(\d+)/.exec(url);
+    if (match) {
+      return `#${match[2]}`;
```
Comment (wlach) [inline src/utils/urls.js]: I think returning something like `mozilla/fenix#1234` would be better for GitHub issues (more idiomatic).

File: src/utils/urls.js [hunk 2]
```diff
@@ -0,0 +1,17 @@
...
+    }
+    return url;
```
Comment (wlach) [inline src/utils/urls.js]: I don't think this is necessary.

```suggestion
```

**Review by wlach — CHANGES_REQUESTED** [review]
One suggested change.

File: src/utils/urls.js (hunk 2 above)
Comment (robhudson) [reply src/utils/urls.js]: This is if it's a link that isn't bugzilla or github so it doesn't show the link as `undefined`, just in case.

File: src/utils/urls.js (hunk 1 above)
Comment (robhudson) [reply src/utils/urls.js]: This makes the links long and breaks the UI, but I can make each of those on their own row to allow for longer URL text...

Screenshot_2020-10-16 storage_stats_cache_bytes GLAM
