### PR TITLE
fixes the scalar visualizations post-bucketing changes

### LINKED ISSUE #397: scalars require a rescaling to match the new-ish buckets
The buckets for the scalar have been extended to go above what we had before. Currently the bounds seem to be set by the percentiles and not the buckets. This should be an easy update.

### PR DESCRIPTION
**Pull request by hamilton**
closes #397

### CODE REVIEW

**Comment by hamilton** [comment]
@openjck @spasovski could one of y'all take on reviewing this sometime this week? I think this should only need one of y'all.

File: src/components/explore/AggregationComparisonGraph.svelte [hunk 1]
```diff
@@ -109,14 +109,14 @@ text: 'Shows the distribution of the current reference point on the line chart',
 alignment: 'center',
       }}
     />
+  </g>
+  <g slot=body let:left let:right let:top let:bottom>
     <slot name='body'
-      left={left} 
-      right={right} 
-      top={top} 
+      left={left}
```
Comment (spasovski) [inline src/components/explore/AggregationComparisonGraph.svelte:115]: alternatively `{left}` etc... from https://svelte.dev/tutorial/dynamic-attributes

**Review by spasovski — APPROVED** [review]
looks good thanks!
